all:
  children:
    oci_vms:
      hosts:
        vrm_server:
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -i ../.secret/id_rsa_cloud -p 22 {{ bastion_session_id }}@host.bastion.sa-vinhedo-1.oci.oraclecloud.com"'
          ansible_user: ubuntu
          ansible_host: 10.1.10.10
          ansible_python_interpreter: /usr/bin/python3
