---
- name: Add main nginx configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: /mnt/volume/nginx/
    owner: "{{ ansible_user }}"
    group: root
    mode: '0644'

- name: Add nginx conf.d configuration
  ansible.builtin.copy:
    src: conf.d/
    dest: /mnt/volume/nginx/conf.d/
    owner: "{{ ansible_user }}"
    group: root
    mode: '0644'

- name: Add nginx html folder
  ansible.builtin.copy:
    src: html/
    dest: /mnt/volume/nginx/html
    owner: "{{ ansible_user }}"
    group: root
    mode: '0644'

- name: Restart / Start Nginx container
  community.docker.docker_container:
    name: "nginx"
    image: "nginx:latest"
    state: started
    restart: yes
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/mnt/volume/nginx/html:/usr/share/nginx/html"
      - "/mnt/volume/nginx/conf.d:/etc/nginx/conf.d"
      - "/mnt/volume/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
  tags: containers
