containers:
  - name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "/mnt/volume/nginx/html:/usr/share/nginx/html"
      - "/mnt/volume/nginx/conf.d:/etc/nginx/conf.d"
      #- "/mnt/volume/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"