---
- name: Deploy application containers
  hosts: oci_vms
  tasks:
    - name: Ensure containers are running
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        ports: "{{ item.ports | default(omit) }}"
        volumes: "{{ item.volumes | default(omit) }}"
      loop: "{{ containers }}"
      tags: containers
