---
- name: Copy docker-compose.yml file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: "{{ compose_all_dir }}"
    owner: "{{ ansible_user }}"
    group: root
    mode: '0644'

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ compose_all_dir }}"
  register: compose_output

- name: Show docker-compose up results
  ansible.builtin.debug:
    var: compose_output