---
- name: Add main nginx configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: /mnt/volume/nginx/
    owner: "{{ ansible_user }}"
    group: root
    mode: '0644'
  notify: 
    - Restart nginx

- name: Add all nginx conf.d configurations
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/mnt/volume/nginx/conf.d/{{ item.path }}'
    owner: "{{ ansible_user }}"
    group: root
    mode: '0644'
  with_community.general.filetree: '../templates/conf.d/'
  when: item.state == 'file'
  notify: 
    - Restart nginx

- name: Add nginx html folder
  ansible.builtin.copy:
    src: html/
    dest: /mnt/volume/nginx/html
    owner: "{{ ansible_user }}"
    group: root
    mode: '0644'
  notify: 
    - Restart nginx