name: Oracle CI - Infra Deployment
on:
  push:
    branches: ["main"]

jobs:
  env:
    OCI_REGION: ${{ vars.OCI_REGION }}
    OCI_TENANCY_OCID: ${{ secrets.OCI_TENANCY_OCID }}
    OCI_USER_OCID: ${{ secrets.OCI_USER_OCID }}
    OCI_COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }}
    OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
    OCI_FINGERPRINT: ${{ vars.OCI_FINGERPRINT }}
    OCI_STATE_PREAUTH_URL: ${{ secrets.OCI_STATE_PREAUTH_URL }}
    BASTION_PUBLIC_KEY_CONTENT: ${{ vars.BASTION_PUBLIC_KEY_CONTENT }}
  run_plan:
    name: "Run Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Configure Credentials & Secrets
        run: |
          mkdir -p ~/.oci
          echo "$OCI_PRIVATE_KEY" > ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/oci_api_key.pem
          echo "address=\"$OCI_STATE_PREAUTH_URL\"" > ./infra/backend.config

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init -backend-config="./backend.config" --reconfigure

      - id: plan
        name: Terraform Plan
        working-directory: ./infra
        run: terraform plan -var "tenancy_ocid=$OCI_TENANCY_OCID" -var "user_ocid=$OCI_USER_OCID" -var "private_key_path=~/.oci/oci_api_key.pem" -var "fingerprint=$OCI_FINGERPRINT" -var "region=$OCI_REGION" -var "compartment_id=$OCI_COMPARTMENT_ID"
  apply_changes:
    name: "Apply Terraform Plan"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -auto-approve -var "tenancy_ocid=$OCI_TENANCY_OCID" -var "user_ocid=$OCI_USER_OCID" -var "private_key_path=~/.oci/oci_api_key.pem" -var "fingerprint=$OCI_FINGERPRINT" -var "region=$OCI_REGION" -var "compartment_id=$OCI_COMPARTMENT_ID"
